"""
Unit tests for the data cleaning utilities contained in
``transfer_genius/data/clean_fbref.py``.  These tests exercise the
``limpiar_df_fbref`` function with a small sample dataset.  The goal is to
validate that summary rows are removed, duplicates are dropped and that
basic sanitisation on key columns occurs.  Keeping these functions
well‑tested helps prevent subtle data quality regressions in the pipeline.
"""
from __future__ import annotations

import pandas as pd

from transfer_genius.data.clean_fbref import limpiar_df_fbref


def test_limpiar_df_fbref_removes_summary_and_duplicates():
    """Rows labelled as squad or opponent totals should be filtered out and
    duplicate player records removed.

    The ``limpiar_df_fbref`` function is designed to drop summary rows
    generated by FBref (e.g. ``Squad Total`` or ``Opponent Total``) and
    deduplicate any repeated entries.  This test builds a small dataframe
    containing a normal player row and two summary rows as well as a
    duplicate of the player.  After cleaning there should only be the
    single player entry remaining.
    """
    df = pd.DataFrame(
        {
            "Player": ["Player1", "Squad Total", "Opponent Total", "Player1"],
            "Nation": ["ESP", "ESP", "ESP", "ESP"],
            "Season": ["2017-2018", "2017-2018", "2017-2018", "2017-2018"],
            "Team": ["TeamA", "TeamA", "TeamA", "TeamA"],
        }
    )
    cleaned = limpiar_df_fbref(df)
    # Expect a single remaining row for the real player
    assert len(cleaned) == 1
    assert cleaned.iloc[0]["Player"] == "Player1"


def test_limpiar_df_fbref_normalises_columns():
    """The cleaning routine should normalise nation and season fields.

    This test validates a couple of the normalisation behaviours.  The
    ``Nation`` column should be reduced to its uppercase code and
    ``Season`` should replace hyphens with slashes.  It also asserts
    that missing team information is filled in.
    """
    df = pd.DataFrame(
        {
            "Player": ["Alice"],
            "Nation": ["Spain (ESP)"],
            "Season": ["2019-2020"],
            "Team": [None],
        }
    )
    cleaned = limpiar_df_fbref(df)
    assert cleaned.loc[0, "Nation"] == "ESP"
    assert cleaned.loc[0, "Season"] == "2019/2020"
    assert cleaned.loc[0, "Team"] != None